#ifndef __ALOBE__CONFIGURATION__
#define __ALOBE__CONFIGURATION__

#define LAND_WIDTH 10
#define LAND_HEIGHT 10
#define INITIAL_BEING_NUMBER 100

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 800
#define FRAMERATE 60
#define BEING_TURNOVER 0.2

#define BACKGROUND_COLOR 0xffffff
#define GRID_COLOR 0x808080
#define GRID_THICKNESS 2
#define LAND_PADDING 50
#define TITLE_PADDING 15
#define BEING_RADIUS 5
#define BEING_NAME_SIZE 15
#define BEING_NAME_SPACING 5
#define BEING_NAME_COLOR 0x000000
#define BEING_COLOR 0xec0000
#define SICK_BEING_COLOR 0x78ab46
#define TITLE_COLOR 0x000000
#define FONT_PATH "/Users/Alex/Scripts/Alobe/Quicksand.otf"

#define BEING_MAXIMUM_AGE 20

#endif // __ALOBE__CONFIGURATION__
