#ifndef __ALOBE__CONFIGURATION__
#define __ALOBE__CONFIGURATION__

// Font
#define FONT_PATH "/Users/Alex/Scripts/Alobe/Quicksand.otf"

// Land
#define LAND_WIDTH 31
#define LAND_HEIGHT 31
#define INITIAL_MEDIAN_DENSITY 1

// Age
#define BEING_MAXIMUM_AGE 120
#define BEING_MATE_RATIO 0.8
#define BEING_MINIMUM_MATE_AGE 20
#define BEING_MAXIMUM_MATE_AGE 45

// Disease
#define DISEASE_TRANSMISSION 0.5
#define DISEASE_REMISSION 0.05
#define DISEASE_ALWAYS_DEAD 20
#define DISEASE_INITIAL_RADIUS 2

// Window
#define WINDOW_WIDTH 1200
#define WINDOW_HEIGHT 800

// Animation
#define FRAMERATE 60
#define BEING_TURNOVER 0.1

// Paddings
#define GRID_THICKNESS 2
#define LAND_PADDING 50
#define TEXT_PADDING 15
#define TITLE_TEXT_HEIGHT 30
#define TEXT_HEIGHT 20
#define BEING_RADIUS 4
#define INFORMATION_PADDING 50
#define INFORMATION_WIDTH (WINDOW_WIDTH - WINDOW_HEIGHT - INFORMATION_PADDING)

// Colors
#define GRID_COLOR 0xcccccc
#define BEING_COLOR 0x4a90e2
#define SICK_BEING_COLOR 0xd0021b
#define ON_CLICK_BEING_COLOR 0x175daf
#define ON_CLICK_SICK_BEING_COLOR 0x9d0000
#define TEXT_COLOR 0x000000

#endif // __ALOBE__CONFIGURATION__
